---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: bento/oracle-7.3
    driver:config:
      vm_hostname: balrog

suites:
  - name: director
    run_list:
      - recipe[segulja_spacewalk::default]
      - recipe[segulja_bacula::director]
      - recipe[segulja_bacula::storage]
      - recipe[segulja_bacula::database]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
